### PR TITLE
add US/ND/fallturkey.json

### PR DESCRIPTION
**Pull request by kdough03**
ValueError: Support only 1 file in archive file /var/folders/gl/9wjcyk215xb4dns_6mc5jpj00000gp/T/tmpqtnvaYnd-fall-turkey.zip when no explicit in-archive filename is specified
You could try one of the following :
  /vsizip//var/folders/gl/9wjcyk215xb4dns_6mc5jpj00000gp/T/tmpqtnvaYnd-fall-turkey.zip/NDGISHubData
  /vsizip//var/folders/gl/9wjcyk215xb4dns_6mc5jpj00000gp/T/tmpqtnvaYnd-fall-turkey.zip/NDGISHubData/NDGAMEFISH_UNIT_TURKEYFALL_polygon.dbf
  /vsizip//var/folders/gl/9wjcyk215xb4dns_6mc5jpj00000gp/T/tmpqtnvaYnd-fall-turkey.zip/NDGISHubData/NDGAMEFISH_UNIT_TURKEYFALL_polygon.prj
  /vsizip//var/folders/gl/9wjcyk215xb4dns_6mc5jpj00000gp/T/tmpqtnvaYnd-fall-turkey.zip/NDGISHubData/NDGAMEFISH_UNIT_TURKEYFALL_polygon.shp
  /vsizip//var/folders/gl/9wjcyk215xb4dns_6mc5jpj00000gp/T/tmpqtnvaYnd-fall-turkey.zip/NDGISHubData/NDGAMEFISH_UNIT_TURKEYFALL_polygon.shx

### CODE REVIEW

**Comment by kdough03** [comment]
Processing error - not a zip file. Need to download/email from GIS portal.

**Comment by kdough03** [comment]
All zip files downloaded from the ND portal appear to be bad; they say that the zip file is empty when I try unzip it via the command line. They convert to .cpgz files when I try to extract them in Finder/the typical way. My Windows machine also shows the zip file as empty. Contacted the pertinent govt agency to ask if I could download or gain access to the ND hunt unit boundaries in another way on 8.18.

**Comment by JesseCrocker** [comment]
I got a totally different error on this file, related to the coordinates being 3d instead of 2d as expected. Processing has been updated to support the 3d coordinates, it flattens them to 2d.

**Comment by JesseCrocker** [comment]
Merged

**Pull request closed without merging**
