### PR TITLE
add US/UT/all.json

### PR DESCRIPTION
**Pull request by backpkr1**

### CODE REVIEW

**Comment by nathancahill** [comment]
The ID field for this shapefile would be IDNUM

**Comment by kdough03** [comment]
Exception: Found multiple shapefiles in zipfile.

**Comment by kdough03** [comment]
Contacted DWRcomment@utah.gov to request the maps/data at http://wildlife.utah.gov/hunting-in-utah/hunt-boundary-maps.html in shp/zip format.

**Comment by kdough03** [comment]
Will be replaced by new PRs for individual species files at http://dwrcdc.nr.utah.gov/ucdc/DownloadGIS/disclaim.htm.

**Pull request closed without merging**
